name: /mnt/home/dforeman/research/projects/exoplanet-dev/case-studies/env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astropy=4.0.1.post1=py37h7b6447c_1
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.14=hb2f20db_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pip=20.0.2=py37_3
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - setuptools=46.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.4
    - arviz==0.7.0
    - astroquery==0.4
    - attrs==19.3.0
    - autograd==1.3
    - babel==2.8.0
    - backcall==0.1.0
    - batman-package==2.4.6
    - beautifulsoup4==4.9.0
    - black==19.10b0
    - black-nbconvert==0.2.0
    - bleach==3.1.5
    - bs4==0.0.1
    - celerite==0.3.1
    - cffi==1.14.0
    - cfgv==3.1.0
    - cftime==1.1.3
    - chardet==3.0.4
    - click==7.1.2
    - corner==2.0.1
    - coverage==5.1
    - coveralls==2.0.0
    - cryptography==2.9.2
    - cython==0.29.17
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distlib==0.3.0
    - docopt==0.6.2
    - docutils==0.16
    - emcee==3.0.2
    - entrypoints==0.3
    - fbpca==1.0
    - filelock==3.0.12
    - flake8==3.8.1
    - future==0.18.2
    - h5py==2.10.0
    - html5lib==1.0.1
    - identify==1.4.15
    - idna==2.9
    - imagesize==1.2.0
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jedi==0.17.0
    - jeepney==0.4.3
    - jinja2==2.11.2
    - json5==0.9.4
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyterlab==2.1.2
    - jupyterlab-server==1.1.3
    - jupytext==1.4.2
    - keyring==21.2.1
    - lightkurve==1.9.1
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.2.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - nbsphinx==0.7.0
    - nbstripout==0.3.7
    - netcdf4==1.5.3
    - nodeenv==1.3.5
    - nose==1.3.7
    - notebook==6.0.3
    - oktopus==0.1.2
    - packaging==20.3
    - pandoc==1.0.2
    - pandocfilters==1.4.2
    - parameterized==0.7.4
    - parso==0.7.0
    - pathspec==0.8.0
    - patsy==0.5.1
    - pep517==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.1.2
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - ply==3.11
    - pre-commit==2.4.0
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - py==1.8.1
    - pybind11==2.5.0
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pyflakes==2.2.0
    - pygments==2.6.1
    - pymc3==3.8
    - pyrsistent==0.16.0
    - pytest==5.4.2
    - pytest-cov==2.8.1
    - pytest-env==0.6.2
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - radvel==1.4.0
    - readme-renderer==26.0
    - rebound==3.12.1
    - rebound-pymc3==0.0.3
    - regex==2020.5.14
    - requests==2.23.0
    - requests-toolbelt==0.9.1
    - scipy==1.3.3
    - secretstorage==3.1.2
    - send2trash==1.5.0
    - setuptools-scm==3.5.0
    - snowballstemmer==2.0.0
    - soupsieve==2.0
    - sphinx==3.0.3
    - sphinx-typlog-theme==0.8.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - starry==1.0.0
    - terminado==0.8.3
    - testpath==0.4.4
    - theano==1.0.4
    - toml==0.10.1
    - tqdm==4.46.0
    - traitlets==4.3.3
    - twine==3.1.1
    - typed-ast==1.4.1
    - uncertainties==3.1.2
    - urllib3==1.25.9
    - virtualenv==20.0.20
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xarray==0.15.1
    - zipp==3.1.0
prefix: /mnt/home/dforeman/research/projects/exoplanet-dev/case-studies/env

